core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("products/", include("products.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views


app_name = "products"
urlpatterns = [
    path("", views.product_list_view, name="list"),
    path("create/", views.product_create_view, name="create"),
    path("<slug:handle>/", views.product_detail_view, name="detail"),
]

products/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Product(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)
    # stripe_product_id
    image = models.ImageField(upload_to="products/", blank=True, null=True)
    name = models.CharField(max_length=200)
    handle = models.SlugField(unique=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=9.99)
    og_price = models.DecimalField(max_digits=10, decimal_places=2, default=9.99)
    # stripe_price_id
    stripe_price = models.IntegerField(default=999)
    price_changed_timestamp = models.DateTimeField(
        auto_now=False, auto_now_add=False, blank=True, null=True
    )
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if self.price != self.og_price:
            # price changed
            self.og_price = self.price
            # trigger an API request for the price
            self.stripe_price = int(self.price * 100)
            self.price_changed_timestamp = timezone.now()
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return f"/products/{self.handle}/"

products/forms.py
from django import forms
from .models import Product

input_css_class = "form-control"


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ["name", "handle", "price"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs["class"] = input_css_class


class ProductUpdateForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ["image", "name", "handle", "price"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs["class"] = input_css_class

products/views.py
from django.shortcuts import redirect, render, get_object_or_404

# Create your views here.
from .forms import ProductForm, ProductUpdateForm
from .models import Product


def product_create_view(request):
    context = {}
    form = ProductForm(request.POST or None)
    if form.is_valid():
        obj = form.save(commit=False)
        if request.user.is_authenticated:
            obj.user = request.user
            obj.save()
            return redirect("/products/create/")
        else:
            form.add_error(None, "User must be logged in")
    context["form"] = form
    return render(request, "products/create.html", context)


def product_list_view(request):
    object_list = Product.objects.all()
    return render(request, "products/list.html", {"object_list": object_list})


def product_detail_view(request, handle=None):
    obj = get_object_or_404(Product, handle=handle)
    is_owner = False
    if request.user.is_authenticated:
        is_owner = obj.user == request.user
    context = {"object": obj}
    form = ProductUpdateForm(request.POST or None, request.FILES or None, instance=obj)
    if form.is_valid():
        obj = form.save(commit=False)
        obj.save()
        # return redirect("/products/create/")
    context["form"] = form
    return render(request, "products/detail.html", context=context)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% include 'base/css.html' %}

    <title>{% block head_title %}Micro eCommerce{% endblock head_title %}</title>

</head>

<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>

    {% include 'base/navbar.html' %}

    <div class="container mx-auto mt-4 min-h-screen">

        {% block content %}
        {% endblock content %}
    </div>

    {% include 'base/footer.html' %}
    {% include 'base/js.html' %}

</body>

</html>

templates/base/css.html
{% load static %}

{# COMMENT: css/output.css comes from the tailwind output #}
<link rel="stylesheet" href="{% static 'css/output.css' %}" />


{# COMMENT: vendor_css_files comes from cfehome.context_processors.vendor_files #}
{% for css_file in vendor_css_files %}
<link rel="stylesheet" href="{% static css_file %}">
{% endfor %}

templates/base/footer.html
<footer class=" bg-white rounded-lg shadow m-4 dark:bg-gray-800">
    <div class="w-full mx-auto container md:p-6 p-4 md:flex md:items-center md:justify-between">
      <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2023 <a href="/" class="hover:underline">Micro eCommerce</a>. All Rights Reserved.
    </span>
    <ul class="flex flex-wrap items-center mt-3 text-sm text-gray-500 dark:text-gray-400 sm:mt-0">
        <li>
            <a href="#" class="mr-4 hover:underline md:mr-6 ">About</a>
        </li>
        <li>
            <a href="#" class="mr-4 hover:underline md:mr-6">Privacy Policy</a>
        </li>
        <li>
            <a href="#" class="mr-4 hover:underline md:mr-6">Licensing</a>
        </li>
        <li>
            <a href="#" class="hover:underline">Contact</a>
        </li>
    </ul>
    </div>
</footer>

templates/base/js.html
{% load static %}

{# COMMENT:  vendor_js_files comes from cfehome.context_processors.vendor_files #}
{% for js_file in vendor_js_files %}
    <script src="{% static js_file %}" preload></script>
{% endfor %}

templates/base/navbar.html
<nav class="bg-white border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-gray-900">
    <div class="container flex flex-wrap items-center justify-between mx-auto">
      <a href="/" class="flex items-center">
          <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">Micro eCommerce</span>
      </a>
      <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
      </button>
      <div class="hidden w-full md:block md:w-auto" id="navbar-default">
        <ul class="flex flex-col p-4 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
          <li>
            <a href="/" class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent" >Home</a>
          </li>
          
          <li>
            <a href="{% url 'products:list' %}" class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Products</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  

templates/home.html
{% extends "base.html" %}


{% block content %}
<div class="flex flex-col items-center justify-center px-6 mx-auto md:h-screen lg:py-0">
<div class="text-center sm:max-w-md w-full mx-auto">
<h1 class="mb-4 text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-6xl dark:text-white">eCommerce with <span class="text-blue-600 dark:text-blue-500">Python</span> has never been easier.</h1>

</div>
</div>

{% endblock %}

templates/products/create.html
{% extends "base.html" %}

{% block content %}

<form method="POST" action=".">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit" class="btn-submit mt-2">Submit</button>
</form>

{% endblock %}

templates/products/detail.html
{% extends "base.html" %}

{% block content %}
    <div class="flex flex-col lg:flex-row">
        <div class="w-full md:w-3/4 space-y-4">
            <!-- main content -->

            <h2 class="text-4xl font-bold dark:text-white">{{ object.name }}</h2>


            <p class="mb-3 text-gray-500 dark:text-gray-400 first-line:uppercase first-line:tracking-widest first-letter:text-7xl first-letter:font-bold first-letter:text-gray-900 dark:first-letter:text-gray-100 first-letter:mr-3 first-letter:float-left">
                Track work across the enterprise through an open, collaborative platform. Link issues across Jira and
                ingest data from other software development tools, so your IT support and operations teams have richer
                contextual information to rapidly respond to requests, incidents, and changes.</p>
            <p class="text-gray-500 dark:text-gray-400">Deliver great service experiences fast - without the complexity
                of traditional ITSM solutions.Accelerate critical development work, eliminate toil, and deploy changes
                with ease, with a complete audit trail for every change.</p>


        </div>

        <div class="w-full md:w-1/4 space-y-4">
            <! -- sidebar -->

            <div class="flex items-baseline text-gray-900 dark:text-white">
                <span class="text-3xl font-semibold">$</span>
                <span class="text-5xl font-extrabold tracking-tight">49</span>
            </div>

            <button type="button"
                    class="focus:outline-none text-white bg-purple-700 hover:bg-purple-800 focus:ring-4 focus:ring-purple-300 font-medium rounded-lg text-sm px-5 py-2.5 mb-2 dark:bg-purple-600 dark:hover:bg-purple-700 dark:focus:ring-purple-900">
                Buy Now
            </button>
            {% if object.image %}
                <div class="grid gap-4">
                <div>
                    <img class="h-auto max-w-full rounded-lg"
                         src="{{ object.image.url }}" alt="">
                </div>
            {% endif %}

            {% if form %}
                <div>
                    <h3>Update Product</h3>
                    <form method="POST" action="." enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}

                        <button type="submit" class="btn-submit mt-2">Submit</button>
                    </form>
                </div>
            {% endif %}

            </div>
        </div>

{% endblock %}

templates/products/list-card.html
<div class="items-center bg-gray-50 rounded-lg shadow sm:flex dark:bg-gray-800 dark:border-gray-700">
    {% if object.image %}<a href="{{ object.get_absolute_url }}">
        <img class="w-full  md:w-64 rounded-lg sm:rounded-none sm:rounded-l-lg" src="{{ object.image.url }}" alt="{{ object.name }}">
    </a>
    {% endif %}
    <div class="p-5">
        <h3 class="text-xl font-bold tracking-tight text-gray-900 dark:text-white">
            <a href="{{ object.get_absolute_url }}">{{ object.name }}</a>
        </h3>
        <span class="text-gray-500 dark:text-gray-400">{{ object.handle }}</span>
        <p class="mt-3 mb-4 font-light text-gray-500 dark:text-gray-400">{{ object.description }}</p>
        <a href="{{ object.get_absolute_url }}" class="text-blue-700 hover:text-white border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-500 dark:focus:ring-blue-800">View Product</a>
    </div>
</div>

templates/products/list.html
{% extends "base.html" %}


{% block content %}

<section class="bg-white dark:bg-gray-900">
    <div class="py-8 px-4 mx-auto max-w-screen-xl lg:py-16 lg:px-6 ">
        <div class="mx-auto max-w-screen-sm text-center mb-8 lg:mb-16">
            <h2 class="mb-4 text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">Products</h2>
            <p class="font-light text-gray-500 lg:mb-16 sm:text-xl dark:text-gray-400">Explore the whole collection of digital products in Micro eCommerce.</p>
        </div>
        <div class="grid gap-8 mb-6 lg:mb-16 md:grid-cols-2">
            {% for object in object_list %}
                {% include 'products/list-card.html' with object=object %}
            {% endfor %}

        </div>
    </div>
  </section>

{% endblock %}